// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxjzlVDrNqlcniGuiBlqJcx4PNkw5oodk',
    appId: '1:1032546225690:web:f90ade2d5d6326118ecba3',
    messagingSenderId: '1032546225690',
    projectId: 'moneyquest-45d2e',
    authDomain: 'moneyquest-45d2e.firebaseapp.com',
    storageBucket: 'moneyquest-45d2e.firebasestorage.app',
    measurementId: 'G-57X8W9PK44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCalty-DsKj2hJYAqErmckvxUyTGL9byAY',
    appId: '1:1032546225690:android:26d1c69e680f1d4f8ecba3',
    messagingSenderId: '1032546225690',
    projectId: 'moneyquest-45d2e',
    storageBucket: 'moneyquest-45d2e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpqigd7ZX_k8lhLEZRfI-8pcIYqsANKQ',
    appId: '1:1032546225690:ios:877bb1636a48066f8ecba3',
    messagingSenderId: '1032546225690',
    projectId: 'moneyquest-45d2e',
    storageBucket: 'moneyquest-45d2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSavemoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpqigd7ZX_k8lhLEZRfI-8pcIYqsANKQ',
    appId: '1:1032546225690:ios:877bb1636a48066f8ecba3',
    messagingSenderId: '1032546225690',
    projectId: 'moneyquest-45d2e',
    storageBucket: 'moneyquest-45d2e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationSavemoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxjzlVDrNqlcniGuiBlqJcx4PNkw5oodk',
    appId: '1:1032546225690:web:c861af7c3a7374f48ecba3',
    messagingSenderId: '1032546225690',
    projectId: 'moneyquest-45d2e',
    authDomain: 'moneyquest-45d2e.firebaseapp.com',
    storageBucket: 'moneyquest-45d2e.firebasestorage.app',
    measurementId: 'G-C7G9BNH4V7',
  );
}
